/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISemaphoreVerifier2_2 } from "./ISemaphoreVerifier2_2"
export type { ISemaphoreVerifier8_2 } from "./ISemaphoreVerifier8_2"
