/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SemaphoreVoting } from "./SemaphoreVoting";
export type { SemaphoreWhistleblowing } from "./SemaphoreWhistleblowing";
