/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ChainIdWithType,
  ChainIdWithTypeInterface,
} from "../../../contracts/base/ChainIdWithType";

const _abi = [
  {
    inputs: [],
    name: "EVM_CHAIN_ID_TYPE",
    outputs: [
      {
        internalType: "bytes2",
        name: "",
        type: "bytes2",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getChainId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getChainIdType",
    outputs: [
      {
        internalType: "uint48",
        name: "",
        type: "uint48",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_resourceId",
        type: "bytes32",
      },
    ],
    name: "parseChainIdFromResourceId",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ChainIdWithType__factory {
  static readonly abi = _abi;
  static createInterface(): ChainIdWithTypeInterface {
    return new utils.Interface(_abi) as ChainIdWithTypeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainIdWithType {
    return new Contract(address, _abi, signerOrProvider) as ChainIdWithType;
  }
}
