version: "3.9"

services:
    graph-node:
        image: graphprotocol/graph-node
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8020:8020"
            - "8030:8030"
            - "8040:8040"
        depends_on:
            - ipfs
            - postgres
        environment:
            postgres_host: postgres
            postgres_user: graph-node
            postgres_pass: let-me-in
            postgres_db: graph-node
            postgres_port: 5432
            ipfs: "ipfs:5001"
            ethereum: "localhost:http://host.docker.internal:8545" # Should use the `localhost` as network name in subgraph.yml
            # ethereum: 'goerli:https://goerli.infura.io/v3/YOUR-API-KEY'
            GRAPH_LOG: info
            GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 1
        networks:
            - the-graph

    ipfs:
        image: ipfs/go-ipfs:v0.4.23
        ports:
            - "5001:5001"
        volumes:
            - graph-ipfs:/data/ipfs
        networks:
            - the-graph

    postgres:
        image: postgres
        ports:
            - "5433:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        environment:
            POSTGRES_USER: graph-node
            POSTGRES_PASSWORD: let-me-in
            POSTGRES_DB: graph-node
            POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
        networks:
            - the-graph
        volumes:
            - graph-postgres:/var/lib/postgresql/data

networks:
    the-graph:
        internal: false
        driver: bridge

volumes:
    graph-postgres:
    graph-ipfs:
