/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Pairing__factory } from "./Pairing__factory";
export { Verifier22__factory } from "./Verifier22__factory";
