/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as incrementalMerkleTreeSol from "./incremental-merkle-tree.sol";
export type { incrementalMerkleTreeSol };
