name: coverall

on:
  push:
    branches:
      - main

env:
  TREE_DEPTH: 20

jobs:
  coverall:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: YARN_CHECKSUM_BEHAVIOR=ignore yarn

      - name: Download Snark artifacts
        run: yarn download:snark-artifacts

      - name: Compile contracts
        run: yarn compile

      - name: Test contracts with coverage
        run: yarn test:coverage

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
